# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ParameterViewer
                                 A QGIS plugin
 This is a plugin to view paremeters
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-08-22
        copyright            : (C) 2025 by -
        email                : ddbakker at ziggo dot nl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ParameterViewer class from file ParameterViewer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .parameter_viewer_plugin import ParameterViewer
    return ParameterViewer(iface)
